name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Linux Xvfb & X11 setup
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev xvfb
          # Generate Xauthority file
          touch ~/.Xauthority
          xauth generate :0 . trusted
          echo "DISPLAY=:0" >> $GITHUB_ENV

      - name: Run tests
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            Xvfb :0 -screen 0 1024x768x24 > /dev/null 2>&1 &
            sleep 5  # Allow Xvfb to start
            go test -v ./...
          else
            go test -v ./...
          fi