name: Test
on: [push, pull_request]


concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.21", "1.22", "1.23"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go (${{ matrix.go }})
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Linux Xvfb & X11 setup
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev xvfb
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run tests
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 5
          xauth generate :99 . trusted > /dev/null 2>&1
            go test -v ./...
          else
            go test -v ./...
          fi